In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings as wr
wr.filterwarnings('ignore')

In [3]:
df = pd.read_csv('/content/weight-height.csv')
df.head()

Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

In [4]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [5]:
df.Gender = le.fit_transform(df[['Gender']])

In [6]:
df.head()

Gender     Height      Weight
0       1  73.847017  241.893563
1       1  68.781904  162.310473
2       1  74.110105  212.740856
3       1  71.730978  220.042470
4       1  69.881796  206.349801

In [7]:
df.tail()

Gender     Height      Weight
8550       0  60.483946  110.565497
8551       0  63.423372  129.921671
8552       0  65.584057  155.942671
8553       0  67.429971  151.678405
8554       0  60.921791  131.253738

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8555 entries, 0 to 8554
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Gender  8555 non-null   int64  
 1   Height  8555 non-null   float64
 2   Weight  8555 non-null   float64
dtypes: float64(2), int64(1)
memory usage: 200.6 KB


In [9]:
df.describe()

Gender       Height       Weight
count  8555.000000  8555.000000  8555.000000
mean      0.584454    66.809925   165.632735
std       0.492845     3.851454    32.043922
min       0.000000    54.616858    65.780000
25%       0.000000    63.957684   139.876803
50%       1.000000    66.985923   168.521567
75%       1.000000    69.604427   190.666305
max       1.000000    80.450000   269.989698

In [10]:
x= df[['Gender','Height']]
y= df['Weight']

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=42)

In [12]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [13]:
lr.fit(X_train,y_train)

LinearRegression()

In [14]:
y_pred_train = lr.predict(X_train)
y_pred_train

array([178.35427565, 202.22486558, 129.22191775, ..., 139.34406368,
       187.17224616, 158.78183812])

In [15]:
y_pred_test = lr.predict(X_test)
y_pred_test

array([142.44868114, 186.0517281 , 198.42283706, ..., 102.94080643,
       190.83713617, 143.34786753])

In [16]:
train_accuracy = lr.score(X_train,y_train)
train_accuracy

0.8973793060969246

In [17]:
test_accuracy = lr.score(X_test,y_test)
test_accuracy

0.905911242442266

In [18]:
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [20]:
lr_mse_test = mean_squared_error(y_test,y_pred_test)
lr_mse_test

96.8373443783061

In [21]:
from sklearn.neighbors import KNeighborsRegressor

In [22]:
kn = KNeighborsRegressor(n_neighbors=5)

In [23]:
kn.fit(X_train,y_train)

KNeighborsRegressor()

In [24]:
kn_y_pred_train = kn.predict(X_train)
kn_y_pred_train

array([176.58174146, 205.54968066, 129.31875904, ..., 142.55470934,
       192.1316955 , 162.1670885 ])

In [25]:
kn_y_pred_test = kn.predict(X_test)
kn_y_pred_test

array([142.1445657 , 181.38276924, 187.07075266, ..., 101.79654426,
       192.43702356, 145.3632227 ])

In [26]:
kn_accuracy_train = kn.score(X_train,y_train)
kn_accuracy_train

0.9172142723737918

In [27]:
kn_accuracy_test = kn.score(X_test,y_test)
kn_accuracy_test

0.8821086423439015

In [28]:
kn_mse_test = mean_squared_error(y_test,kn_y_pred_test)
kn_mse_test

121.33528273624482

In [31]:
compare_model = pd.DataFrame({'Model':['Linear Regression','KNN'],'Train Accuracy':[train_accuracy,kn_accuracy_train],'Test Accuracy':[test_accuracy,kn_accuracy_test],'Test MSE':[lr_mse_test,kn_mse_test]})
compare_model

Model  Train Accuracy  Test Accuracy    Test MSE
0  Linear Regression        0.897379       0.905911   96.837344
1                KNN        0.917214       0.882109  121.335283